Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Razorpay.Api;
using System;
using LibraryManagementSystem.Models;
using LibraryManagementSystem.Data;

namespace LibraryManagementSystem.Controllers{
    public class OrderController : Controller{
        private readonly OrderDbContext db5;
        private readonly IssueBookDbContext db1;
        public OrderController(OrderDbContext context3,IssueBookDbContext context){
            db5=context3;
            db1=context;
        }
        [BindProperty]
         public OrderEntity _orders {get; set;}
         public IActionResult Index(){
            return View();
        }
        public IActionResult InitiateOrder(OrderEntity orders){

            string key = "rzp_test_y3d9ISew6fCzvG";
            string secret = "CVfBShvnIZ4ZFMyQNebKZ6au";


            Random _random=new Random();
            string TransactionId=_random.Next(0,10000).ToString();
             

           Dictionary<string, object> input = new Dictionary<string, object>();
            input.Add("amount",Convert.ToDecimal(_orders.Total_amt )*100); 
            input.Add("currency", "INR");
            input.Add("receipt", "TransactionId");

            RazorpayClient client = new RazorpayClient(key, secret);
            Razorpay.Api.Order order = client.Order.Create(input);

            ViewBag.Orderid= order["id"].ToString();
            orders.OrderId = order["id"].ToString();
            orders.TransactionId = "";
            orders.PaymentStatus = "Pending";
            db5.orderEntities.Add(orders);
            db5.SaveChanges();

            return View("Payment",_orders);
        }
//         public IActionResult Payment(int BookID,string razorpay_payment_id,string razorpay_order_id){

//      Dictionary<string, string> attributes = new Dictionary<string, string>();  

//      attributes.Add("razorpay_payment_id",razorpay_payment_id);
//      attributes.Add("razorpay_order_id",razorpay_order_id);

//     OrderEntity ord = new OrderEntity();
//     ord.TransactionId=razorpay_payment_id;
//     ord.OrderId=razorpay_order_id;
//     ord.PaymentStatus="Paid";
    

//     if (razorpay_payment_id !=null)
//     {
//         ord.TransactionId=razorpay_payment_id;
//         ord.OrderId=razorpay_order_id;
//         ord.PaymentStatus="Paid";
//     }
//     db5.orderEntities.Update(ord);
//     db5.SaveChanges();

//     return View("Paymentsuccess",ord);
// }
public IActionResult Payment(int BookID,string razorpay_payment_id,string razorpay_order_id){
    Dictionary<string, string> attributes = new Dictionary<string, string>();  
    attributes.Add("razorpay_payment_id",razorpay_payment_id);
    attributes.Add("razorpay_order_id",razorpay_order_id);

    OrderEntity ord = db5.orderEntities.FirstOrDefault(o => o.OrderId == razorpay_order_id);
    IssueBook issueBook = db1.IssueBooks.FirstOrDefault(ib => ib.EmailID == ord.Email && ib.Penalty == ord.Total_amt);
    if (ord != null)
    {
        ord.TransactionId = razorpay_payment_id;
        ord.OrderId=razorpay_order_id;
        ord.PaymentStatus = "Paid";
        db5.orderEntities.Update(ord);
        db5.SaveChanges();


        if (ord.PaymentStatus == "Paid" && issueBook != null) {
            issueBook.PaymentStatus = "Paid";
            issueBook.OrderId = ord.OrderId;
            
            // Update the issue book record in the database
            db1.IssueBooks.Update(issueBook);
            db1.SaveChangesAsync();
        }
    }

// Update the penalty status in the issue book record if the order has been paid
    return View("Paymentsuccess",ord);
    // else
    // {
    //     // handle order not found error
    //     return View("PaymentError");
    // }
}

    }
}

Controllers/UserController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LibraryManagementSystem.Models;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace LibraryManagementSystem.Controllers;

public class UserController : Controller
{
    private readonly UserDetailDbContext db;
    private readonly BorrowBookDbContext DB;
    private readonly IssueBookDbContext db1;
    private readonly BookDbContext dB;
    private readonly IWebHostEnvironment _environment;
    public UserController(IssueBookDbContext context3,BorrowBookDbContext context1,BookDbContext Context,UserDetailDbContext context, IWebHostEnvironment environment)
    {
        DB= context1;
        db = context;
        dB = Context;
        db1=context3;
        _environment = environment;
    }


    [HttpGet]

    public IActionResult UserHomePage()
    {
        return View();
    }

    [HttpGet]

    public async Task<IActionResult> Indexs()

    {

        var email = HttpContext.Session.GetString("EmailID");
        UserDetail u = await db.UserDetails.Where(x => x.EmailID == email).FirstOrDefaultAsync();
        //   var li = from s in db.UserDetails
        //              where s.EmailID == email
        //              select s;

        return View(u);
        //  return View(await li.AsNoTracking().ToListAsync());
    }
    // public async Task<IActionResult> BorrowBook(BookRequest bookRequest, int id)
    // {
    //     var email = HttpContext.Session.GetString("EmailID");
    //     UserDetail u = await db.UserDetails.Where(x => x.EmailID == email).Select(x => new UserDetail { EmailID = x.EmailID, Name = x.Name }).FirstOrDefaultAsync();
    //     Book b = await Db.Books.Where(x => x.ID == id).Select(x => new Book { BookID = x.BookID, BookName = x.BookName, BookEdition = x.BookEdition }).FirstOrDefaultAsync();
    //     var request = new BookRequest { User = u, Book = b };
    //     _db.BookRequests.Add(request);
    //     await _db.SaveChangesAsync();
    //     return View();
    // }
  

public async Task<IActionResult> BorrowBook(int BookID)
{
    // Retrieve the current user
    var email = HttpContext.Session.GetString("EmailID");
    UserDetail user = await db.UserDetails.FirstOrDefaultAsync(u => u.EmailID == email);

    // Retrieve the book based on the bookID value
    Book book = await dB.Books.FirstOrDefaultAsync(b => b.BookID == BookID);

    // Create a new BorrowedBook object
    BorrowBook borrowedBook = new BorrowBook
    {
        BookID = book.BookID,
        BookName = book.BookName,
        BookEdition = book.BookEdition,
        Name = user.Name,
        EmailID = user.EmailID,
        Date = DateTime.Now,
        BookStatus="Borrowed"
    };

    // Add the new BorrowedBook object to the database and save changes
    DB.BorrowBooks.Add(borrowedBook);
    await DB.SaveChangesAsync();

    // Redirect the user back to the Books view
    return RedirectToAction("UserHomePage");
}
    [HttpGet]


    public IActionResult Index()
    {
        return View("MainIndex", "Category");
    }
    public IActionResult LoginPage()
    {
        return View();
    }
    public IActionResult AdminHomePage()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }



[HttpGet]

        public async Task<IActionResult> IssueBookDetails(string sortOrder, string searchString, string currentFilter, int? pageNumber)

        {



            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;


            var email = HttpContext.Session.GetString("EmailID");
          var li = from s in db1.IssueBooks
                     where s.EmailID == email
                     select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                li = li.Where(s => s.Name.Contains(searchString)
                                       || s.EmailID.Contains(searchString)
                                       || s.BookName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    li = li.OrderByDescending(s => s.Name);
                    break;
                default:
                    li = li.OrderBy(s => s.BookEdition);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<IssueBook>.CreateAsync(li.AsNoTracking(), pageNumber ?? 1, pageSize));
            //  return View(await li.AsNoTracking().ToListAsync());
        }
        
 public async Task<IActionResult> ReturnBook(int BookID)
 {       
     IssueBook issueBook = await db1.IssueBooks.FirstOrDefaultAsync(b => b.BookID == BookID);

     // Retrieve the book based on the bookID value
        issueBook.ReturnDate=DateTime.Now;
        issueBook.Issued="Returned";
        if (issueBook.DueDate < issueBook.ReturnDate)
        {
            TimeSpan diff = issueBook.ReturnDate - issueBook.DueDate;
            double daysOverdue = diff.TotalDays; // Penalty rate per day
            double penaltyAmount = daysOverdue * 2;
            issueBook.Penalty = Math.Round(penaltyAmount, 2);
            issueBook.PaymentStatus="Pending";
        }
 
     // Add the new IssueBook object to the database and save changes
     db1.IssueBooks.Update(issueBook);
     await db1.SaveChangesAsync();

     // // Remove the book from the BorrowBooks table
     // Redirect to the AdminHomePage action
    return RedirectToAction("UserHomePage");
 }
}

Views/User/IssueBookDetails.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@using LibraryManagementSystem.Models
@model PaginatedList<LibraryManagementSystem.Models.IssueBook>
    @{
    var email = HttpContextAccessor.HttpContext.Session.GetString("EmailID");
}

@{
    ViewData["Title"] = "Index";
}

<header style="margin-bottom: 40px;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  ">
            <div class="container-fluid">
                <img src="https://th.bing.com/th/id/OIP.c7gLBJpEuUBJ0qsmkcCQgwAAAA?pid=ImgDet&rs=1" style="height:60px;width:140px"  alt="LOGO">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li></ul>
                          <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ">
                        
                        <a class="greeting nav-link text-dark" style="color: rgb(187, 26, 26);">  Welcome  @HttpContextAccessor.HttpContext.Session.GetString("EmailID")</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="UserLogOut"><b>LogOut</b></a>
                        </li>
                    </ul>
                </div>
                         
                        </div>
                  
            </div>
        </nav>
    </header>
    <div class="container">
    <div style="border:1px solid black;box-shadow:13px 9px 32px 2px blanchedalmond;padding:10px;">

        <form asp-action="IssueBookDetails" method="get">
            <div class="form-actions no-color">
                <p style="margin-top:20px">
                    <input type="text" name="SearchString" value="@ViewData["currentFilter"]" placeholder="Search by BookName,Issue Status" style="font-size: 15px; width: 200px" />
                    <input type="submit" value="Search" class="btn btn-outline-success btn-sm" /> |
                    <a asp-action="Index">Back to Full List</a>
                </p>
            </div>
        </form>

        @if (Model == null)
        {
            <h1 style="color:red;text-align:center">No data Found</h1>

        }
        else
        {
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>EmailID</th>
                        <th>BookID</th>
                        <th>BookName</th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]"> <span class="glyphicon glyphicon-sort"> BookEdition</span>  </a>

                        </th>
                        <th>duedate</th>
                        <th>Issued</th>
                        <th>return</th>
                        <th>Penalty</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.EmailID</td>
                            <td>@item.BookID</td>
                            <td>@item.BookName</td>
                            <td>@item.BookEdition</td>
                            <td>@item.DueDate</td>
                            <td>@item.Issued</td>
                            <td>
                                @if (item.Issued == "Yes")
                                {
                                    <form asp-controller="User" asp-action="ReturnBook" method="post">
                                        <input type="hidden" name="BookID" value="@item.BookID" />
                                        <button type="submit" class="btn btn-primary">return</button>
                                    </form>
                                }
                                else
                                {
                                    <button type="button" class="btn btn-primary" disabled>return</button>
                                }
                            </td>
                            <td>
                                @if (item.DueDate < item.ReturnDate && item.PaymentStatus != "Paid")
                                {
                                    TimeSpan diff = item.ReturnDate - item.DueDate;
                                    double daysOverdue = diff.TotalDays;
                                    double penaltyAmount = daysOverdue * 10; // Assuming penalty is $10 per day
                                    <span asp-for="penaltyAmount">₹@penaltyAmount.ToString("N2")</span>
                                    <form action="@Url.Action("Index", "Order")" method="post">
                                        <button type="submit" class="btn btn-warning" data-bs-toggle="tooltip" data-bs-placement="top" title="Penalty Amount: ₹@penaltyAmount.ToString("N2")">Pay Penalty</button>
                                    </form>
                                }
                                else if (item.PaymentStatus == "Paid")
                                {
                                    <span>Paid</span>
                                }
                                else
                                {
                                    <span>NILL</span>
                                }
                            </td>


                </tr>
                    }
                </tbody>
            </table>    
        }
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }

        <a asp-action="IssueBookDetails"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="IssueBookDetails"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>
    </div>
            
         
@*@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@model PaginatedList<LibraryManagementSystem.Models.IssueBook>
    @{
    var email = HttpContextAccessor.HttpContext.Session.GetString("EmailID");
}

@{
    ViewData["Title"] = "Index";
}

<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  ">
            <div class="container-fluid">
                <img src="https://th.bing.com/th/id/OIP.c7gLBJpEuUBJ0qsmkcCQgwAAAA?pid=ImgDet&rs=1" style="height:60px;width:140px"  alt="LOGO">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li></ul>
                          <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CSharpBook" asp-action="Index"><b>Books</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserDetail" asp-action="Index"><b>User</b></a>
                        </li>
                        <a class="greeting nav-link text-dark" style="color: rgb(187, 26, 26);">  Welcome  @HttpContextAccessor.HttpContext.Session.GetString("EmailID")</a>
                    </ul>
                </div>
                         
                        </div>
                  
            </div>
        </nav>
    </header>
    <div style="border:1px solid black;box-shadow:13px 9px 32px 2px blanchedalmond;padding:10px;">

        <a asp-action="Create" class="btn btn-primary btn-block">Create New</a>
        <form asp-action="Index" method="get">
            <div class="form-actions no-color">
                <p style="margin-top:20px">
                    <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
                    <input type="submit" value="Search" class="btn btn-outline-success btn-sm" /> |
                    <a asp-action="Index">Back to Full List</a>
                </p>
            </div>
        </form>

        @if (Model == null)
        {
            <h1 style="color:red;text-align:center">No data Found</h1>

        }
        else
        {
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>EmailID</th>
                        <th>BookID</th>
                        <th>BookName</th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]"> <span class="glyphicon glyphicon-sort"> BookEdition</span>  </a>

                        </th>
                        <th>duedate</th>
                        <th>Issued</th>
                        <th>return</th>
                        <th>Penalty</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.EmailID</td>
                            <td>@item.BookID</td>
                            <td>@item.BookName</td>
                            <td>@item.BookEdition</td>
                            <td>@item.DueDate</td>
                            <td>@item.Issued</td>
                            <td><form asp-controller="User" asp-action="ReturnBook" method="post">
                                    <input type="hidden" name="BookID" value="@item.BookID" />
                                    <button type="submit" class="btn btn-primary">return</button>
                                </form>
                            </td>
                            <td>
                                @if (item.DueDate < item.ReturnDate)
                                {
                                    TimeSpan diff = item.ReturnDate - item.DueDate;
                                    double daysOverdue = diff.TotalDays;
                                    double penaltyAmount = daysOverdue * 10; // Assuming penalty is $10 per day
                                    <span asp-for="penaltyAmount">₹@penaltyAmount.ToString("N2")</span>
                                    <form action="@Url.Action("Index", "Order")" method="post">
                                        <button type="submit" class="btn btn-warning" data-bs-toggle="tooltip" data-bs-placement="top" title="Penalty Amount: ₹@penaltyAmount.ToString("N2")">Pay Penalty</button>
                                    </form>

                                }
                                else
                                {
                                    <span>NILL</span>
                                }
                            </td>



                </tr>
                    }
                </tbody>
            </table>    
        }
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }

        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    </div>

            
         
*@

Views/User/UserHomePage.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Multi Login";
}
<html>
<head>
        <meta http-equiv='refresh'content="10000;url=https://localhost:7087/Main/SessionExpired" />
<style>
    body{
        background-image: url("https://appsamurai.com/wp-content/uploads/2018/04/shutterstock_1231981675.jpg");
        background-repeat: no-repeat;
        background-attachment: fixed;
  background-size: cover;
    }
table, td, th {
  text-align: center;
  border: 1px solid white;
  align-items: center;
}

table {
  border-collapse: collapse;
  width: 80%;
  text-align: center;
}

td {
  text-align: center;
}
table.center {
  margin-left: auto; 
  margin-right: auto;
}
h2 {
  color: rgb(0, 0, 0);
  font-family: 'Times New Roman', Times, serif;
  font-size: 300%;
  text-align:center;

}
</style>
</head>
 <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  ">
            <div class="container-fluid">
                <img src="https://th.bing.com/th/id/OIP.c7gLBJpEuUBJ0qsmkcCQgwAAAA?pid=ImgDet&rs=1" style="height:60px;width:140px"  alt="LOGO">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                        </ul>
                          </ul>
                              </div>
                         
                          <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="MainIndex"><b>Books</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="IssueBookDetails"><b>BookIssued</b></a>
                        </li>
                        <a class="greeting nav-link text-dark" style="color: rgb(187, 26, 26);">  Welcome  @HttpContextAccessor.HttpContext.Session.GetString("EmailID")</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Indexs"><b>Profile</b></a>
                        </li>
                    </ul>
                </div>
                        </div>
                  
            </div>
        </nav>
    </header>
<body >



</body>
</html>