Models/UserDetail.cs
 using System;
 using System.Collections.Generic;
 using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace LibraryManagementSystem.Models
{

public class UserDetail
{
    public int ID { get; set; }
    public string? ProfilePicture { get; set; }

    [Required(ErrorMessage = "Register number is required")]
    [RegularExpression(@"^(?!0{1,3})\d{5,9}$", ErrorMessage = "Register Number must be between 5 and 9 digits and it should not contain one or more zeros at First.")]
    public string RegisterNo { get; set; }

    [Required(ErrorMessage = "Name is required")]
    [RegularExpression(@"^(?:[A-Z][a-z]+(?:\s|$))+[A-Z](?:\s[A-Z])*$", ErrorMessage = "Name must be in this format 'Name Initial'")]
    public string Name { get; set; }



    [Required(ErrorMessage = "Email ID is required")]
    [RegularExpression(@"^[a-z][a-z0-9._%+-]+@gmail\.com$", ErrorMessage = "Invalid Email Address")]
    public string EmailID { get; set; }

    [Required(ErrorMessage = "Password is required")]
    [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*\W)(?!.*\s).{8,15}$", ErrorMessage = "Password must contain at least one uppercase letter, one lowercase letter, one number, one symbol, and be 8-15 characters long.")]
    public string Password { get; set; }


    [Required(ErrorMessage = "Gender is required")]
    public string Gender { get; set; }

    [Required(ErrorMessage = "Age is required")]
    [Range(18, int.MaxValue, ErrorMessage = "Age must be above 18.")]
    public int Age { get; set; }

    [Required(ErrorMessage = "Address is required")]
    public string Address { get; set; }

    [Required(ErrorMessage = "Phone number is required")]
    [RegularExpression(@"^[7-9][0-9]{9}$", ErrorMessage = "Please enter a valid mobile number.")]

    public string PhoneNumber { get; set; }

    
}
}

Controllers/UserDetailController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using LibraryManagementSystem.Models;
using LibraryManagementSystem.Data;
using LibraryManagementSystem.Interfaces;
using System.Net.Mail;
using System.Net;
using Microsoft.AspNetCore.Authorization;

namespace LibraryManagementSystem.Controllers
{
    [Authorize]
    public class UserDetailController : Controller
    {
        private readonly UserDetailDbContext db;
        private readonly IUserRepository _userRepository;
        private readonly IWebHostEnvironment _environment;
        public UserDetailController(UserDetailDbContext context, IWebHostEnvironment environment, IUserRepository userRepository)
        {
            db = context;
            _environment = environment;
            _userRepository = userRepository;
        }


        [HttpGet]

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)

        {



            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;


            var li = from s in db.UserDetails
                     select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                li = li.Where(s => s.Name.Contains(searchString)
                                       || s.EmailID.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    li = li.OrderByDescending(s => s.Name);
                    break;
                default:
                    li = li.OrderBy(s => s.RegisterNo);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<UserDetail>.CreateAsync(li.AsNoTracking(), pageNumber ?? 1, pageSize));
            //  return View(await li.AsNoTracking().ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {

            UserDetail u = new UserDetail();

            return View(u);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserDetail ui, IFormFile file)
        {
        if (ModelState.IsValid)
        {
            if (await db.UserDetails.AnyAsync(x => x.EmailID == ui.EmailID))
            {
                ModelState.AddModelError("EmailID", "Email ID already exists");
            }

            // Check if register number already exists
            if (await db.UserDetails.AnyAsync(x => x.RegisterNo == ui.RegisterNo))
            {
                ModelState.AddModelError("RegisterNo", "Register number already exists");
            }
            if (await db.UserDetails.AnyAsync(x => x.PhoneNumber == ui.PhoneNumber))
            {
                ModelState.AddModelError("PhoneNumber", "PhoneNumber already exists");
            }
            if (!ModelState.IsValid)
            {
                return View(ui);
            }

        // If there are any validation errors, return the view with the errors
        // if (!ModelState.IsValid)
        // {
        //     return View(ui);
        // }
            UserDetail u = new UserDetail();
            if (file == null || file.Length == 0)
            {
                u.ProfilePicture = "NoImage.png";
            }
            else
            {
                string filename = System.Guid.NewGuid().ToString() + ".png";
                var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot", "images", filename);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                u.ProfilePicture = filename;

            }
            u.RegisterNo = ui.RegisterNo;
            u.Name = ui.Name;
            u.EmailID = ui.EmailID;
            u.Password = ui.Password;
            u.Gender = ui.Gender;
            u.Age = ui.Age;
            u.Address = ui.Address;
            u.PhoneNumber = ui.PhoneNumber;
            
            db.UserDetails.Add(u);
            await db.SaveChangesAsync();

        var senderEmail = new MailAddress("murugaiyanlatha6@gmail.com", "Swedha M");
        var receiverEmail = new MailAddress(ui.EmailID, ui.Name);
        var password = "mmnuuajpcizuambd";
        var subject = "Welcome to the Library";
        var body = "Dear " + ui.Name + ",\n\nGreetings From LMS! \n\nHope you are doing well.\n\nWelcome to the Digital Library Management System. We have created an account for you on our platform to provide you with the necessary learning resources. Find the login credentials below. \n\nEmailID:" + ui.EmailID + "\n\nPassword:" + ui.Password +"\n\nThank you.";
        var smtp = new SmtpClient
        {
            Host = "smtp.gmail.com",
            Port = 587,
            EnableSsl = true,
            DeliveryMethod = SmtpDeliveryMethod.Network,
            UseDefaultCredentials = false,
            Credentials = new NetworkCredential(senderEmail.Address, password)
        };
        using (var message = new MailMessage(senderEmail, receiverEmail)
        {
            Subject = subject,
            Body = body
        })
        {
            smtp.Send(message);
        }

            return RedirectToAction("Index");

        }
        return View(ui);
    }

        [HttpGet]

        public async Task<IActionResult> Edit(int? id)

        {

            if (id == null)

            {

                return NotFound();

            }



            UserDetail u = await db.UserDetails.Where(x => x.ID == id).FirstOrDefaultAsync();





            if (u == null)

            {

                return NotFound();

            }



            return View(u);

        }







        [HttpPost]

        public async Task<IActionResult> Edit(int? id, UserDetail ui, IFormFile file)

        {

            if (id == null)

            {

                return NotFound();

            }



            UserDetail u = await db.UserDetails.Where(x => x.ID == id).FirstOrDefaultAsync();



            if (u == null)

            {

                return NotFound();

            }





            if (file != null || file.Length != 0)

            {



                string filename = System.Guid.NewGuid().ToString() + " .png";

                var path = Path.Combine(

                            Directory.GetCurrentDirectory(), "wwwroot", "images", filename);



                using (var stream = new FileStream(path, FileMode.Create))

                {

                    await file.CopyToAsync(stream);

                }


                if (db.UserDetails.Any(x => x.EmailID == ui.EmailID && x.ID != id) || 
                    db.UserDetails.Any(x => x.RegisterNo == ui.RegisterNo && x.ID != id) ||
                    db.UserDetails.Any(x => x.PhoneNumber == ui.PhoneNumber && x.ID != id))
                {
                    // A user with the same email or registration number already exists in the database
                    ModelState.AddModelError(string.Empty, "A user with the same email or registration number already exists.");
                    return View(ui);
                }
                u.ProfilePicture = filename;



            }
            u.RegisterNo = ui.RegisterNo;
            u.Name = ui.Name;
            u.EmailID = ui.EmailID;
            u.Password = ui.Password;
            u.Gender = ui.Gender;
            u.Age = ui.Age;
            u.Address = ui.Address;
            u.PhoneNumber = ui.PhoneNumber;
            await db.SaveChangesAsync();



        var senderEmail = new MailAddress("murugaiyanlatha6@gmail.com", "Swedha M");
        var receiverEmail = new MailAddress(ui.EmailID, ui.Name);
        var password = "zxbkpznmcqrxnebn";
        var subject = "Details Updation";
        var body = "Dear " + ui.Name + ",\n\nGreetings From LMS! \n\nHope you are doing well.\n\nWelcome to the Digital Library Management System. We have created an account for you on our platform to provide you with the necessary learning resources. Find the login credentials below. \n\nEmailID:" + ui.EmailID + "\n\nPassword:" + ui.Password +"\n\nThank you.";
        var smtp = new SmtpClient
        {
            Host = "smtp.gmail.com",
            Port = 587,
            EnableSsl = true,
            DeliveryMethod = SmtpDeliveryMethod.Network,
            UseDefaultCredentials = false,
            Credentials = new NetworkCredential(senderEmail.Address, password)
        };
        using (var message = new MailMessage(senderEmail, receiverEmail)
        {
            Subject = subject,
            Body = body
        })
        {
            smtp.Send(message);
        }


            return RedirectToAction("Index");







        }



        [HttpGet]


        public async Task<IActionResult> Details(int? id)


        {

            if (id == null)

            {

                return NotFound();

            }



            UserDetail u = await db.UserDetails.Where(x => x.ID == id).FirstOrDefaultAsync();





            if (u == null)

            {

                return NotFound();

            }



            return View(u);

        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || db.UserDetails == null)
            {
                return NotFound();
            }

            var UserDetails = await db.UserDetails
                .FirstOrDefaultAsync(m => m.ID == id);
            if (UserDetails == null)
            {
                return NotFound();
            }

Views/UserDetail/Create.cshtml
  @model LibraryManagementSystem.Models.UserDetail

@{
    ViewData["Title"] = "Create";
}

<header style="margin-bottom: 40px;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  ">
            <div class="container-fluid">
                <img src="https://th.bing.com/th/id/OIP.c7gLBJpEuUBJ0qsmkcCQgwAAAA?pid=ImgDet&rs=1" style="height:60px;width:140px"  alt="LOGO">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li></ul>
                          <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut"><b>LogOut</b></a>
                        </li> 
                    </ul>
                </div>
                         
                        </div>
                  
            </div>
        </nav>
    </header>
<h1 style="text-align:center">Add New User</h1>


<hr />



<div class="row">
    <div class="col-md-11 mx-auto">
        <form asp-action="Create" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="col-md-6 ">
                    <div class="form-group">
                        <label asp-for="RegisterNo" class="control-label"></label>
                        <input asp-for="RegisterNo" class="form-control" />
                        <span asp-validation-for="RegisterNo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="EmailID" class="control-label"></label>
                        <input asp-for="EmailID" class="form-control" />
                        <span asp-validation-for="EmailID" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">  
                        <label asp-for="Gender" class="control-label"></label>  
                        <select asp-for="Gender" class="form-control">  
                            <option value="">Choose Gender</option>  
                            <option value="Male">Male</option>  
                            <option value="Female">Female</option>  
                        </select>  
                        <span asp-validation-for="Gender" class="text-danger"></span>  
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input asp-for="Age" class="form-control" />
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input type="file" name="file" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form-group"style="text-align:center">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/UserDetail/Delete.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@using LibraryManagementSystem.Models
@model UserDetail
   
@{


    ViewData["Title"] = "Delete";


}

<!DOCTYPE html>

<html>
    <header style="margin-bottom: 40px;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  ">
            <div class="container-fluid">
                <img src="https://th.bing.com/th/id/OIP.c7gLBJpEuUBJ0qsmkcCQgwAAAA?pid=ImgDet&rs=1" style="height:60px;width:140px"  alt="LOGO">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li></ul>
                          <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut"><b>LogOut</b></a>
                        </li>    
                    </ul>
                </div>
                         
                        </div>
                  
            </div>
        </nav>
    </header>
<body>

<h3>Are you sure you want to delete this User?</h3>
<hr/>
<div class="container">
    
    <dl class="row" style="border:1px solid black;box-shadow:20px 20px 50px 20px;padding:35px">

        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.ProfilePicture)

        </dt>

        <dd class = "col-sm-15">

         

            <img src="~/images/@Model.ProfilePicture" style="height:100px;width:100px"/>

        </dd>
        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.RegisterNo)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.RegisterNo)

        </dd>

        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.Name)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.Name)

        </dd>

        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.EmailID)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.EmailID)

        </dd>
        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.Password)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.Password)

        </dd>
        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.Gender)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.Gender)

        </dd>
        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.Age)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.Age)

        </dd>
        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.Address)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.Address)

        </dd>
        <dt class = "col-sm-2">

            @Html.DisplayNameFor(model => model.PhoneNumber)

        </dt>

        <dd class = "col-sm-15">

            @Html.DisplayFor(model => model.PhoneNumber)

        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/UserDetail/Index.cshtml
@using LibraryManagementSystem.Models
@model PaginatedList<LibraryManagementSystem.Models.UserDetail>
@{
    ViewData["Title"] = "Index";
}


<header style="margin-bottom: 40px;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  ">
            <div class="container-fluid">
                <img src="https://th.bing.com/th/id/OIP.c7gLBJpEuUBJ0qsmkcCQgwAAAA?pid=ImgDet&rs=1" style="height:60px;width:140px"  alt="LOGO">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li></ul>
                          <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut"><b>LogOut</b></a>
                        </li> 
                    </ul>
                </div>
                         
                        </div>
                  
            </div>
        </nav>
    </header>
<div class="container">
    <div style="border:1px solid black;box-shadow:13px 9px 32px 2px blanchedalmond;padding:10px;">

        <a asp-action="Create" class="btn btn-primary btn-block">Create New</a>
        <form asp-action="Index" method="get">
            <div class="form-actions no-color">
                <p style="margin-top:20px">
                    <input type="text" name="SearchString" value="@ViewData["currentFilter"]" placeholder="Search User by Name/Email" style="font-size: 15px; width: 200px" />
                    <input type="submit" value="Search" class="btn btn-outline-success btn-sm" /> |
                    <a asp-action="Index">Back to Full List</a>
                </p>
            </div>
        </form>

        @if (Model == null)
        {
            <h1 style="color:red;text-align:center">No data Found</h1>

        }
        else
        {
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>RegisterNo.</th>
                        <th>Profile</th>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]"> <span class="glyphicon glyphicon-sort"> Name</span>  </a>

                        </th>
                        <th>EmailID</th>
                        <th>Password</th>
                        <th>Gender</th>
                        <th>Age</th>
                        <th>Address</th>
                        <th>PhoneNumber</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.RegisterNo</td>
                            <td><img src="~/images/@item.ProfilePicture" style="height:70px;width:70px;" /></td>
                            <td>@item.Name</td>
                            <td>@item.EmailID</td>
                            <td>@item.Password</td>
                            <td>@item.Gender</td>
                            <td>@item.Age</td>
                            <td>@item.Address</td>
                            <td>@item.PhoneNumber</td>
                            <td><a asp-action="Edit" class="btn btn-info" asp-route-id="@item.ID">Edit</a></td>
                            <td><a asp-action="Delete"class="btn btn-secondary" asp-route-id="@item.ID">Delete</a></td>
                        </tr>
                    }
                </tbody>
            </table>    
        }
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }

        <a asp-controller="UserDetail" asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-controller="UserDetail" asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
    
    </div>
</div>

            
        